### ISSUE TITLE
main 브랜치에 merge시 2번 action이 돌아가는 이슈

### ISSUE THREAD

**Issue by SeungIlB** [Gyeongditor/story-field-be#12]
## 📝 이슈 요약
타 브랜치에서 main 브랜치로 merge시 Git action CI가 두번씩 돌아가는 이슈 발생

## 🧾 발생 배경
```
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
```
위와 같이 main에 push시, main이 PR 요청시 CI가 돌아가게끔 설정이 되어 있었음

## 해결 방안
단순하게 push 또는 PR요청시 둘 중 하나의 경우만 CI가 돌아가게끔 설정하면 됨.
따라서 main에 push 되는 경우만 CI가 돌아가게끔 설정
